os: Visual Studio 2017

build_script:
  - cmd: .\build.cmd InstallVSCE
  - cmd: .\build.cmd BuildPackage

test: off

cache:
  - "%LocalAppData%\\NuGet\\Cache -> paket.lock"
  - "node_modules -> yarn.lock"

artifacts:
  - path: temp\*.vsix
    name: Ionide FSharp VSCode Extension